# =================================================================
# APARATO: PNPM WORKSPACE DEFINITION
# ESTADO: CORREGIDO (PACKAGES DEFINED)
# =================================================================

packages:
  - 'apps/*'
  - 'libs/*'
  - 'tools/*'

# Configuración de dependencias compartidas
autoInstallPeers: true

# Optimizaciones de disco
link-workspace-packages: true
prefer-workspace-packages: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - nx
  - sharp
  - unrs-resolver
